# -*- coding: utf-8 -*-
"""SIF Scorer Card Performance Visualizer

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tXxLqtjO0PJ690-360kUHY31HqclsL0j

# <center>School Idol Festival Scorer Performance Visualizer</center>
# <center>Author: Nguyễn Hồng Sơn/Kyrie Nguyen

# I. Miêu tả/Description
(English description below)

Đây là phần mềm biểu diễn số điểm một thẻ scorer có thể buff bằng KĨ NĂNG của thẻ đó trong một bài hát qua nhiều lần chơi khác nhau. Dữ liệu được lấy từ https://sif.kirara.ca/setlist. Biểu đồ có thể KHÁC NHAU qua từng lần chạy.

---
This histogram displays the score a scorer can buff by its SKILL while playing a song throughout many different times. Data taken from https://sif.kirara.ca/setlist. Histograms VARY by different runtimes.

Sample: (Maki Nishikino Candy Level 7)
![Histogram](https://i.imgur.com/huuGzxN.png)

# II. Tác dụng/Benefit
(English reasons below)

Công cụ này nhằm bổ sung thêm cho bảng tham khảo [này](https://docs.google.com/spreadsheets/d/1ZUqGrxlgaprYaUowYCwZ_Za2FdWXdTghxTnQGau7sYs/). Ở đây, các bạn có thể nhanh chóng tra thẻ scorer mình định sưu tầm/đang có bằng cách nhập thông tin thẻ được yêu cầu. Mục đích chính của biểu đồ này là giúp bạn đánh giá khách quan được mức độ ổn định cũng như tiềm năng của thẻ, phù hợp với những bạn muốn tối ưu hóa đội hình của mình hơn để có thể đạt được tier 1 trong score ranking hoặc để khè bạn bè.

---
This histogram was made to further support [this sheet](https://docs.google.com/spreadsheets/d/1ZUqGrxlgaprYaUowYCwZ_Za2FdWXdTghxTnQGau7sYs/). Here, you can immediately search for your dream/possessed scorers by input their information as required. The main purpose of this histogram is to help your analyze the stability and potential of a card, which is more appropriate if you want to further optimize your team to get to first tier in score ranking.

# III. Cài đặt/Settings
(English settings below)

Số lần chơi: 500

Điều kiện bài hát: (sẽ được cập nhật khi Event Master ra bên SIF EN)
- Độ khó: Expert
- Số nốt: 550
- Tỉ lệ PERFECT: 98% (sai số 1%) (những người chơi có khả năng PERFECT dưới 95% KHÔNG nên tham khảo biểu đồ này vì các thẻ scorer được kích hoạt bằng số nốt PERFECT sẽ chạy skill ít hơn dự đoán của biểu đồ này).
- Đã full combo.

Điều kiện thẻ: đã gắn ngọc charm

---
Play count: 500

Song condition: (will be updated when Master Event is available in SIF EN)
- Difficulty: Expert
- Total combo: 550
- PERFECT rate: 98% (with a margin of 1%) (players that cannot play a song with more than 95% PERFECT SHOULD NOT refer to this histogram, as those scorers that are activated by the number of PERFECTS would not activate as often as predicted in this histogram).
- Full combo achieved.

Card condition: attached with charm SIS

#IV. Hướng dẫn sử dụng biểu đồ này/ Instructions on how to use this tool
(English instructions below)

Đầu tiên, ấn vào nút open in playground ở góc trái trên. Bạn sẽ được dẫn sang một trang khác giống hệt trang này (nên đọc hết trang này trước). Ở trang đó, ngay dưới đoạn văn này là code để có thể vẽ ra biểu đồ. Ấn nút có biểu tượng giống nút play trong youtube. Sau đó, các bạn sẽ được kéo xuống phần câu hỏi gồm các thuộc tính của thẻ scorer mà bạn cần tham khảo:
1. Thẻ này có phải chạy trên PERFECT không? - Ấn chữ 'y' là có, ấn chữ 'n' là không
2. Số nốt kích hoạt thẻ
3. Tỉ lệ kích hoạt thẻ - Ở đây các bạn nhập tỉ lệ dưới dạng số thập phân (VD: 58% --> .58)
4. Điểm cho một lần kích hoạt thẻ
5. (Tự chọn) Tên của thẻ - Các bạn có thể đặt tên thẻ như đã được hướng dẫn hoặc ấn enter để skip.

Kết quả trả lại sẽ bao gồm: số điểm cao nhất (max), số điểm thấp nhất (min) mà thẻ buff được, số điểm trung bình mà thẻ có thể buff được, và đồ thị biểu diễn số lần chơi thẻ buff một số điểm nhất định nào đó (dưới dạng khoảng).



Sau khi đồ thị đã được hiển thị, bạn có thể chọn lưu ảnh để có thể so sánh với các thẻ khác.

Bạn có thể tham khảo mẫu ở cuối trang

Tips: 
- Khi so sánh, để ý kĩ trục Ox (số điểm buff) và Oy (số lần chơi) vì nó khác nhau giữa các biểu đồ, và chú ý các cột về phía bên phải của các cột chính (các cột cao nhất) - nó cho thấy tiềm năng có thể đạt được của scorer của bạn.
- Thẻ có rate kích hoạt cao (trên 64%) thì độ ổn định tốt nhưng tiềm năng thấp, phù hợp để hỗ trợ team đạt một mức điểm nhất định và đánh Score Match Event. Ngược lại, thẻ có rate kích hoạt thấp thì không quá ổn định nhưng tiềm năng lớn, phù hợp để đột phá đua score ranking.

---
First, click the button "Open in playground" at the upper left corner. You will be redirected to another page that looks just like this (so it is recommended to finish this page first). In that page, right below this paragraph is the code to draw the histogram. Press the button that looks like the Youtube Play button. You will be dragged to a list of questions that ask for the data of the card you need to know.
1. Does this card base on the number of PERFECT? - Press 'y' for yes, 'n' for no
2. Number of notes for activation
3. Activation rate - Input as a decimal number (Eg: 58% --> .58)
4. Score per activation
5. (Optional) Name of the scorer - You can use the sample name or press enter to skip.

The result includes: the maximum score buff, the minimum score buff, and the mean score buff, and the histogram representing how many times your scorer buff how much score.

After the histogram is displayed, you can choose to save this histogram for later comparison with other card.

You can have a look at the example at the bottom of the page.
Tips: 
- Pay close attention to the x-axis and y-axis as they vary from histogram to histogram, and the column that is next to the right of the main columns (those highest one).
- High activation rate (above 64%) means high stability but low potential, more appropriate for supporting team and Score Event Match. Low activation rate means low stability but very high potential, more appropriate for making breakthrough to get top score in score ranking.
"""

import random
import math
import matplotlib.pyplot as plt
import numpy as np
from scipy import stats
from google.colab import files

def convert_boolean(condition):
    if condition:
        return 1
    return 0
 
def one_time(based, notes, rate, scores):
    buff = 0
    perfect_count = 0
    note_count = 0
    PERFECT_RATE = .98
    for i in range(550):
        note_count += 1
        accuracy = random.uniform(0, 1)
        if accuracy <= PERFECT_RATE:
            perfect_count += 1
        if based == 'PERFECT':
            if perfect_count % notes == 0:
                activation = random.uniform(0, 1)
                buff += scores * 2.5 * convert_boolean(activation < rate)
        else:
            if note_count % notes == 0:
                activation = random.uniform(0, 1)
                buff += scores * 2.5 * convert_boolean(activation < rate)
    return int(buff)

def mean_dev(scores):
  return stats.norm.fit(scores)
  
space = 500
data = []
based = 'NOTE'
if input('Does this card base on PERFECT notes (y/n)? ').lower() == 'y':
         based = 'PERFECT'
notes = int(input("Number of notes for activation: "))
rate = float(input("Rate (in decimal form): ")) 
score = int(input("Score: "))
name = input("Card name (E.g: Maki Nishikino - Candy - Smile - Level 7/ Press enter to skip):\n")
for i in range(space):
    score_this_match = one_time(based, notes , rate, score)
    data.append(score_this_match)

minScore = min(data)
maxScore = max(data)
meanUR = mean_dev(data)
mean = meanUR[0]
UR = meanUR[1] / 1000
print('\nPerformances of this card over {} tries'.format(space))
print('--------------------------')
print('Average score: ', math.ceil(mean))
print('Max score: ', maxScore)
print('Min score: ', minScore)
print('Unstable Rate (UR): ', round(UR, 2))
# storage = open("UR_score_list.txt", 'a+')
# storage.write(name + ': ' + str(math.ceil(mean)) + '\n')

fig = plt.figure(figsize=(15,10))
plt.style.use('ggplot')
binwidth = score * 2.5
xAxis = np.arange(minScore, maxScore + binwidth , binwidth)
plt.xticks(xAxis)
plt.hist(data, bins=xAxis, color='cyan', edgecolor='yellow', linewidth=1)
plt.title(name)
plt.xlabel('Additional score per match')
plt.ylabel('Number of matches')
plt.show()

if input('Do you want to save this picture (y/n)? ').lower() == 'y':
  # fileName = input("File name: ") + '.png'
  # fig.savefig(fileName)
  files.download(input('File name: ') + '.png')

"""Như các bạn có thể thấy, thẻ scorer Maki Candy Skill Level 7 sẽ buff được mức điểm ổn định trong khoảng 98750 cho tới 128375. Nếu bạn may mắn hơn thì tiềm năng có thể lên tới mới 128375 cho tới 148125, thậm chí là có thể cao hơn nữa.

---
As you can see from the histogram above, the Maki Candy Scorer at skill level 7 can buff stablely in the range of 98750 to 128375. If you are lucky enough, her potential can get to the range of 128375 to 148125, and even higher is possible.

# V. Lưu ý thêm/Further notes
(English below)
Các bạn hoàn toàn có thể thay đổi settings trong mục II theo hướng dẫn sau:
- Tay bạn không đủ to để có thể perfect rate được 98%? Trong đoạn code trên, bạn có thể sửa dòng ở bên dưới, thay số .98 thành bất cứ rate nào bạn muốn (dưới dạng số thập phân)

```
# PERFECT_RATE = .98  
```
- Các bạn muốn biết chính xác giá trị kỳ vọng cho một bài hát nhất định? (VD: Zurui yo Magnetic Today) Sửa số combo mặc định thành số combo bài hát bạn muốn biết (VD: 550 - > 533)

```
# for i in range(550):
```
Chúc bạn may mắn trong gacha và xây dựng team mơ ước của mình ^^

---
You guys can change the settings in II by these instructions:
- Change the default perfect rate by changing the .98 in the above code to any rate you want (in decimal form).

```
#PERFECT_RATE = .98
```
- Change the default combo to a specific song combo by changing this piece of code (E.g: Zurui yo Magnetic Today => Change 550 to 533)

```
# for i in range (550):
```
Wish y'all good luck in gacha and build your desired team ^^

## VI. Cập nhật/Update log
(English log below)
- 13/07/2020: thêm "độ thiếu ổn định", được tính bằng phương sai của dữ liệu chia cho 1000 để đánh giá trên thang 0 - 100.

---
- July, 13th 2020: adding "unstable rate", which is calculated by taking the standard derivation of the data divided by 1000 to judge on the scale of 0 - 100
"""